### ISSUE TITLE
В Мастер лежит не актуальная версия проекта

### ISSUE THREAD

**Issue by Kandaulov** [Servek/ivk-site#1]
В мастере лежит дефолтный проект c стартовым шаблоном MVC
Кроме того, у него похоже битые зависимости на библиотеки

**Comment by Servek** [comment]
Да, мы в мастер не делали merge. Самая актуальная версия лежит в dev_t. К
новому году мы сделаем стабильную версию и запушим в мастер.

24 дек. 2016 г. 15:32 пользователь "Валерий" <notifications@github.com>
написал:

**Comment by Kandaulov** [comment]
М.. Пока не вижу обещанный мердж?

**Comment by Servek** [comment]
Извиняюсь, забыл сделать коммит. Сейчас там последняя сборка. Только там тестовое наполнение (lorem ipsum)
